export const metaData = {
    "featuresTitle":"How Does Auto Trading Robot Work?",
    "featuresDesc":"A Trading Auto Trading Robot that works as a fully Automated Trading System that executes both Buy, Sell Trade Automatically & Close the Trade in Profit.",
    "featuresKeywords":"expert advisor features, EA features, features of Trading EA, Trading expert advisor features, features of automated trading, Trading software, automatic trading robot, auto trading software in Singapore, Trading EA in Singapore, trading software in Singapore, robot trading software",
    "faqTitle":"FAQ - Expert Advisor For Trading  | EA - FAQs",
    "faqDesc":"Whether I need to have knowledge of Trading EA trading? No need for trading knowledge. All trading processes will be taken care of by the bot. The client can check the notifications of the amount rising.",
    "faqKeywords":"faq, expert advisor faq, EA, Trading EA faq, frequently asked questions, Trading expert advisor faq, faq for automated trading, Trading software faq, automatic trading robot, auto trading software in Singapore, Trading EA in Singapore, Trading software in Singapore, robot trading software",
    "pricingTitle":"Pricing Plans - Auto Trading Robot",
    "pricingDesc":"price of Trading EA, expert advisor, EA, cost of Trading EA, Trading expert advisor, automated trading, Trading software, automatic trading robot, auto trading software in Singapore, Trading EA in Singapore, trading software in Singapore, robot trading software",
    "pricingKeywords":"price of Trading EA, expert advisor, EA, cost of Trading EA, Trading expert advisor, automated trading, Trading software, automatic trading robot, auto trading software in Singapore, Trading EA in Singapore, trading software in Singapore, robot trading software",
    "supportTitle":"Assistance For Auto Trading Setup",
    "supportDesc":"Ticket Id: Convert all information into tickets. We prioritize, categorize and assign them to the right Department. For Support, We are here 24X7 to support you.",
    "supportKeywords":"Trading Expert advisor support, trading software support, automated trading software setup, Trading EA, expert advisor Trading support, automatic trading robot, best algorithmic trading software, auto trading software in Singapore, auto trading software in India, auto trading software in Singapore",
    "contactTitle":"Contact Us - Auto Trading Robot",
    "contactDesc":"Reach out to us, for additional enquiries about Trading Expert Advisor and its Services. Anything On your Mind. We are here to assist you!",
    "contactKeywords":"contact us, reach us, get in touch with us, contact us for the expert advisor, EA, best trading EA, trading expert advisor contact details, automated trading, trading software, automatic trading robot, contact details for auto trading software in Singapore, details for trading EA in Singapore, trading software in Singapore",
    "getStartedTitle":"Get The Trading Expert Advisor | Trading EA | Expert Advisor",
    "getStartedDesc":"Our company is a software provider organization for Trading expert advisors. Offering automatic Trading robot arrangement with the expert advisor (Trading EA) accounts.",
    "getStartedKeywords":"get the best Trading expert advisor, Trading EA, best Trading EA, Trading expert advisor, automated trading, Trading software, automatic trading robot, auto trading software in Singapore, Trading EA in Singapore, Trading software in Singapore, robot trading software",
    "termsTitle":"Terms and Conditions - Auto Trading Robot",
    "termsDesc":"Any new features or tools which are added to the current store shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page.",
    "termsKeywords":"terms and conditions for Trading EA, terms and conditions for expert advisor, EA terms and conditions, Trading EA terms and conditions, Trading expert advisor, terms of automated trading, Trading software terms, terms and conditions for automatic trading robot, auto trading software in Singapore, Trading EA in Singapore, trading software in Singapore",
    "privacyTitle":"Privacy Policy For Trading Expert Advisor | Trading EA Policies",
    "privacyDesc":"If you have any questions or concerns about our use of your personal information, then please contact us using the contact details provided at the bottom of this Privacy Policy.",
    "privacyKeywords":"privacy policy, privacy statement, privacy and policies for the expert advisor, expert advisor policies, EA, privacy and policy for Trading EA, statement of Trading expert advisor, automated trading, Trading software, automatic trading robot, auto trading software in Singapore",
    "refuncTitle":"Refund Policy For Trading Expert Advisor | Trading EA Trading",
    "refundDesc":"If the product has defected and Not Functioning Maximum of Up to 15 days Refund is Applicable. or otherwise No Refund is issued in this case.",
    "refundKeywords":"refund policy, refund terms and conditions, refund statement, refund conditions for expert advisor, EA, Trading EA refund policy, Trading expert advisor, automated trading, refund policy for Trading software, automatic trading robot, auto trading software in Singapore, Trading EA in Singapore, trading software in Singapore"
}